/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InterestBank } from "./InterestBank";
export * as factories from "./factories";
export { InterestBank__factory } from "./factories/InterestBank__factory";
