/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigWallet } from './MultiSigWallet.js';
export * as factories from './factories/index.js';
export { MultiSigWallet__factory } from './factories/MultiSigWallet__factory.js';