/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MultiSigWalletInterface extends Interface {
    getFunction(nameOrSignature: "isConfirmed" | "isOwner" | "numConfirmationRequired" | "owners" | "submitTransaction" | "transaction"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConfirmTransaction" | "Deposit" | "ExecuteTransaction" | "RevokeConfirmation" | "SubmitTransaction"): EventFragment;

    encodeFunctionData(functionFragment: 'isConfirmed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'numConfirmationRequired', values?: undefined): string;
encodeFunctionData(functionFragment: 'owners', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitTransaction', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'transaction', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'isConfirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'numConfirmationRequired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transaction', data: BytesLike): Result;
  }

  
    export namespace ConfirmTransactionEvent {
      export type InputTuple = [owner: AddressLike, txIndes: BigNumberish];
      export type OutputTuple = [owner: string, txIndes: bigint];
      export interface OutputObject {owner: string, txIndes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish, balanca: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint, balanca: bigint];
      export interface OutputObject {sender: string, amount: bigint, balanca: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecuteTransactionEvent {
      export type InputTuple = [owner: AddressLike, txIndes: BigNumberish];
      export type OutputTuple = [owner: string, txIndes: bigint];
      export interface OutputObject {owner: string, txIndes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevokeConfirmationEvent {
      export type InputTuple = [owner: AddressLike, txIndes: BigNumberish];
      export type OutputTuple = [owner: string, txIndes: bigint];
      export interface OutputObject {owner: string, txIndes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmitTransactionEvent {
      export type InputTuple = [owner: AddressLike, txIndex: BigNumberish, to: AddressLike, value: BigNumberish, data: BytesLike];
      export type OutputTuple = [owner: string, txIndex: bigint, to: string, value: bigint, data: string];
      export interface OutputObject {owner: string, txIndex: bigint, to: string, value: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MultiSigWallet extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultiSigWallet;
    waitForDeployment(): Promise<this>;

    interface: MultiSigWalletInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isConfirmed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    numConfirmationRequired: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    submitTransaction: TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    transaction: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, numConfirmations: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isConfirmed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'numConfirmationRequired'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'submitTransaction'): TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transaction'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, numConfirmations: bigint }],
      'view'
    >;

    getEvent(key: 'ConfirmTransaction'): TypedContractEvent<ConfirmTransactionEvent.InputTuple, ConfirmTransactionEvent.OutputTuple, ConfirmTransactionEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'ExecuteTransaction'): TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
getEvent(key: 'RevokeConfirmation'): TypedContractEvent<RevokeConfirmationEvent.InputTuple, RevokeConfirmationEvent.OutputTuple, RevokeConfirmationEvent.OutputObject>;
getEvent(key: 'SubmitTransaction'): TypedContractEvent<SubmitTransactionEvent.InputTuple, SubmitTransactionEvent.OutputTuple, SubmitTransactionEvent.OutputObject>;

    filters: {
      
      'ConfirmTransaction(address,uint256)': TypedContractEvent<ConfirmTransactionEvent.InputTuple, ConfirmTransactionEvent.OutputTuple, ConfirmTransactionEvent.OutputObject>;
      ConfirmTransaction: TypedContractEvent<ConfirmTransactionEvent.InputTuple, ConfirmTransactionEvent.OutputTuple, ConfirmTransactionEvent.OutputObject>;
    

      'Deposit(address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'ExecuteTransaction(address,uint256)': TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
      ExecuteTransaction: TypedContractEvent<ExecuteTransactionEvent.InputTuple, ExecuteTransactionEvent.OutputTuple, ExecuteTransactionEvent.OutputObject>;
    

      'RevokeConfirmation(address,uint256)': TypedContractEvent<RevokeConfirmationEvent.InputTuple, RevokeConfirmationEvent.OutputTuple, RevokeConfirmationEvent.OutputObject>;
      RevokeConfirmation: TypedContractEvent<RevokeConfirmationEvent.InputTuple, RevokeConfirmationEvent.OutputTuple, RevokeConfirmationEvent.OutputObject>;
    

      'SubmitTransaction(address,uint256,address,uint256,bytes)': TypedContractEvent<SubmitTransactionEvent.InputTuple, SubmitTransactionEvent.OutputTuple, SubmitTransactionEvent.OutputObject>;
      SubmitTransaction: TypedContractEvent<SubmitTransactionEvent.InputTuple, SubmitTransactionEvent.OutputTuple, SubmitTransactionEvent.OutputObject>;
    
    };
  }